apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris-hub-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ganeshsnp987/Tetris-manifest.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: tetris
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
